-- Created by MyysticOwl
-- The use of this code requires the permission of the author.
-- Permission can be atained by contacting MyysticOwl at: TonicBars@gmail.com
--
-- RESPECT!

THEVERSION = "v3.0.1"

QUICKSLOTBAR = 1;
EXTENSIONBAR = 2;
TABBED_INV_BAR = 3;
WINDOW_INV_BAR = 4;

NORMAL_MODE 	= 1;
QUICKSLOT_MODE 	= 2;
EXTENSION_MODE 	= 3;
GENERAL_MODE 	= 4;
ABOUT_MODE 		= 5;
INVENTORY_MODE  = 6;
EASYBAR_MODE 	= 7;
EASYBARTITLE_MODE 	= 8;

SHOW_EXTENSIONS 		= 1;
SELECT_RANDOM_SHORTCUT	= 2;
CYCLE_EXTENSIONS 		= 3;
ROLL_UP_SELECTION 		= 4;
CLICK_CYCLE_EXTENSIONS  = 5;

HUNTER_TRAVEL_TYPE 		= 1;
WARDEN_TRAVEL_TYPE 		= 2;
HOUSING_TRAVEL_TYPE     = 3;
LM_COMBAT_PETS_TYPE 	= 4;
LM_COSMETIC_PETS_TYPE 	= 5;
CAPTAIN_PETS_TYPE 		= 6;
REP_TRAVEL_TYPE			= 7;
HORSE1_TYPE				= 8;
HORSE2_TYPE				= 9;
PONY1_TYPE				= 10;
PONY2_TYPE				= 11;
INSTRUMENTS_TYPE		= 12;
MINI_DPS_TYPE		 	= 13;

TRIGGER_TYPE_CTRL 		= 1;
TRIGGER_TYPE_ALT  		= 2;
TRIGGER_TYPE_SHIFT      = 3;
TRIGGER_TYPE_COMBAT 	= 4;
TRIGGER_TYPE_HEALTH		= 5;
TRIGGER_TYPE_POWER		= 6;
TRIGGER_TYPE_POISON 	= 7;
TRIGGER_TYPE_FEAR		= 8;
TRIGGER_TYPE_WOUND		= 9;
TRIGGER_TYPE_DESEASE	= 10;

TRIGGER_TYPES_EQUAL		= 1;
TRIGGER_TYPES_GT		= 2;
TRIGGER_TYPES_LT		= 3;
TRIGGER_TYPES_BETWEEN	= 4;

CHAMPION_FERVOR = "Fervor";
HUNTER_FOCUS = "Focus";
RK_ATTUNEMENT = "Attunement";